name: exptools
channels:
- defaults
dependencies:
- numpy
- pandas
- pytz
- termcolor
- pip:
  - aiofiles
  - aionotify
  - base58
  - pyomo
  - tzlocal
  - websockets
  - yaql
  - tox # requires conda's virtualenv
- wheel
- pylint
- pytest
- pytest-asyncio
- pytest-cov
- virtualenv
