name: exptools
channels:
- defaults
dependencies:
- pytz
- termcolor
- pip:
  - aiofiles
  - base58
  - tzlocal
  - websockets
  - yaql
  - tox # requires conda's virtualenv
- wheel
- pylint
- pytest
- pytest-cov
- virtualenv
