name: exptools
channels:
- defaults
dependencies:
- pytz
- termcolor
- pandas
- requests
- werkzeug
- pip:
  - base58
  - tzlocal
  - json-rpc
- wheel
- pylint
- pytest
- pytest-cov
- jupyter
- matplotlib
