name: exptools
channels:
- defaults
dependencies:
- pytz
- termcolor
- pip:
  - aiofiles
  - base58
  - tzlocal
  - websockets
  - yaql
- wheel
- pylint
- pytest
- pytest-cov
- jupyter
- matplotlib
- pandas
